// ROUTER
// ROUTER — handled below with Playground support
// AUDIO ENGINE
const AC=window.AudioContext||window.webkitAudioContext;
let ctx=null,mGain=null,mvol=.8;
function iCtx(){if(!ctx){ctx=new AC();mGain=ctx.createGain();mGain.gain.value=mvol;mGain.connect(ctx.destination);}if(ctx.state==='suspended')ctx.resume();}
function mkN(col,dur){const len=Math.ceil(ctx.sampleRate*(dur||.5));const buf=ctx.createBuffer(1,len,ctx.sampleRate);const d=buf.getChannelData(0);let last=0;for(let i=0;i<len;i++){const w=Math.random()*2-1;if(col==='pink'){last=.99886*last+w*.0555179;d[i]=last*3.5;}else d[i]=w;}const s=ctx.createBufferSource();s.buffer=buf;return s;}
function GG(v){const g=ctx.createGain();g.gain.value=v;g.connect(mGain);return g;}
function FF(fr,tp,dest,Q){const f=ctx.createBiquadFilter();f.type=tp||'lowpass';f.frequency.value=fr;if(Q)f.Q.value=Q;f.connect(dest);return f;}
function playDrum(type,vel,when,p){
  if(!ctx)return;const t=Math.max(ctx.currentTime,(when||ctx.currentTime));const v=Math.min(1.3,(vel||.7)*mvol);p=p||{};
  if(type==='bass808'||type==='bass808slide'){const g=GG(v*.92);const fi=FF(p.filterCutoff||200,'lowpass',g,p.filterRes||1);const osc=ctx.createOscillator();osc.type='sine';osc.connect(fi);const bf=p.pitch?110*Math.pow(2,p.pitch/12):82;osc.frequency.setValueAtTime(type==='bass808slide'?bf*1.15:bf,t);osc.frequency.exponentialRampToValueAtTime(bf*.44,t+(p.decay||.4));g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(v*.92,t+(p.attack||.001));g.gain.linearRampToValueAtTime(v*(p.sustain||.6)*.92,t+(p.attack||.001)+(p.decay||.4));g.gain.exponentialRampToValueAtTime(.001,t+(p.attack||.001)+(p.decay||.4)+.25);osc.start(t);osc.stop(t+.8);}
  else if(type.startsWith('kick')){const dec=p.decay||.25;const g=GG(v*.9);const osc=ctx.createOscillator();osc.type='sine';const fi=FF(p.filterCutoff||20000,'lowpass',g);osc.connect(fi);osc.frequency.setValueAtTime(type==='kick_boom'?175:type==='kick_hard'?160:145,t);osc.frequency.exponentialRampToValueAtTime(28,t+dec);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(v*.9,t+(p.attack||.001));g.gain.exponentialRampToValueAtTime(.001,t+dec+(p.release||.05));osc.start(t);osc.stop(t+dec+.15);const cg=GG(v*.3);const cn=mkN('white',.03);cn.connect(FF(4500,'highpass',cg));cg.gain.setValueAtTime(v*.3,t);cg.gain.exponentialRampToValueAtTime(.001,t+.025);cn.start(t);cn.stop(t+.03);}
  else if(type.startsWith('snare')){const dec=p.decay||.15;const ng=GG(v*.7);const noise=mkN('white',dec+.05);const cf=type==='snare_lofi'?1800:type==='snare_fat'?4500:Math.min(p.filterCutoff||7000,7000);noise.connect(FF(cf,'bandpass',ng,p.filterRes||1));ng.gain.setValueAtTime(0,t);ng.gain.linearRampToValueAtTime(v*.7,t+.001);ng.gain.exponentialRampToValueAtTime(.001,t+dec);noise.start(t);noise.stop(t+dec+.05);if(type!=='snare_rim'){const tg=GG(v*.35);const to=ctx.createOscillator();to.type='triangle';to.frequency.value=type==='snare_fat'?215:185;to.connect(tg);tg.gain.setValueAtTime(0,t);tg.gain.linearRampToValueAtTime(v*.35,t+.001);tg.gain.exponentialRampToValueAtTime(.001,t+.1);to.start(t);to.stop(t+.12);}}
  else if(type==='clap'){for(let i=0;i<3;i++){const ti=t+i*.009;const cg=GG(v*.58);const n=mkN('pink',.08);n.connect(FF(4000,'bandpass',cg,.8));cg.gain.setValueAtTime(0,ti);cg.gain.linearRampToValueAtTime(v*.58,ti+.001);cg.gain.exponentialRampToValueAtTime(.001,ti+.07);n.start(ti);n.stop(ti+.09);}}
  else if(type.startsWith('hihat')){const dur=type==='hihat_fast'?.025:type==='hihat_vin'?.05:.045;const d2=p.decay||dur;const hg=GG(v*.38);const noise=mkN('white',d2+.01);noise.connect(FF(10000,'highpass',hg));hg.gain.setValueAtTime(0,t);hg.gain.linearRampToValueAtTime(v*.38,t+.001);hg.gain.exponentialRampToValueAtTime(.001,t+d2);noise.start(t);noise.stop(t+d2+.01);}
  else if(type==='openhat'){const d2=p.decay||.28;const og=GG(v*.34);const n=mkN('white',d2+.1);n.connect(FF(8000,'highpass',og));og.gain.setValueAtTime(0,t);og.gain.linearRampToValueAtTime(v*.34,t+.002);og.gain.linearRampToValueAtTime(v*.08,t+d2*.7);og.gain.exponentialRampToValueAtTime(.001,t+d2);n.start(t);n.stop(t+d2+.05);}
  else if(type==='shaker'){const sg=GG(v*.28);const n=mkN('white',.06);const sf=ctx.createBiquadFilter();sf.type='bandpass';sf.frequency.value=8500;sf.Q.value=3;sf.connect(sg);n.connect(sf);sg.gain.setValueAtTime(0,t);sg.gain.linearRampToValueAtTime(v*.28,t+.005);sg.gain.exponentialRampToValueAtTime(.001,t+.05);n.start(t);n.stop(t+.06);}
  else if(type==='snap'){const sg=GG(v*.62);const o=ctx.createOscillator();o.type='triangle';o.frequency.value=1100;o.connect(sg);const n=mkN('pink',.06);n.connect(FF(3500,'highpass',sg));sg.gain.setValueAtTime(0,t);sg.gain.linearRampToValueAtTime(v*.62,t+.001);sg.gain.exponentialRampToValueAtTime(.001,t+.055);o.start(t);o.stop(t+.06);n.start(t);n.stop(t+.06);}
  else if(type==='rim'){const rg=GG(v*.52);const o=ctx.createOscillator();o.type='triangle';o.frequency.value=850;o.connect(rg);const n=mkN('white',.08);n.connect(FF(5000,'highpass',rg));rg.gain.setValueAtTime(0,t);rg.gain.linearRampToValueAtTime(v*.52,t+.001);rg.gain.exponentialRampToValueAtTime(.001,t+.07);o.start(t);o.stop(t+.08);n.start(t);n.stop(t+.08);}
  else if(type==='brush'){const bg=GG(v*.24);const n=mkN('pink',.22);n.connect(FF(2500,'lowpass',bg));bg.gain.setValueAtTime(0,t);bg.gain.linearRampToValueAtTime(v*.24,t+.015);bg.gain.exponentialRampToValueAtTime(.001,t+.2);n.start(t);n.stop(t+.22);}
  else if(['perc','perc_hard','perc_dark','ethnic'].includes(type)){const freq={perc:240,perc_hard:300,perc_dark:170,ethnic:330}[type];const dur={perc:.13,perc_hard:.13,perc_dark:.22,ethnic:.13}[type];const pg=GG(v*.58);const o=ctx.createOscillator();o.type='triangle';o.frequency.value=freq;o.connect(pg);const n=mkN('pink',dur);n.connect(FF(2500,'bandpass',pg));pg.gain.setValueAtTime(0,t);pg.gain.linearRampToValueAtTime(v*.58,t+.001);pg.gain.exponentialRampToValueAtTime(.001,t+dur);o.start(t);o.stop(t+dur+.02);n.start(t);n.stop(t+dur);}
  else if(type==='tambourine'){for(let i=0;i<4;i++){const ti=t+i*.011;const tg=GG(v*.3);const n=mkN('white',.05);n.connect(FF(11000,'highpass',tg));tg.gain.setValueAtTime(0,ti);tg.gain.linearRampToValueAtTime(v*.3,ti+.001);tg.gain.exponentialRampToValueAtTime(.001,ti+.04);n.start(ti);n.stop(ti+.05);}}
  else if(type==='vinyl'){const vg=GG(v*.14);const n=mkN('pink',.2);n.connect(FF(700,'lowpass',vg));vg.gain.setValueAtTime(v*.14,t);vg.gain.exponentialRampToValueAtTime(.001,t+.18);n.start(t);n.stop(t+.2);}
  else if(type==='scratch'){const sg=GG(v*.52);const o=ctx.createOscillator();o.type='sawtooth';o.connect(sg);o.frequency.setValueAtTime(550,t);o.frequency.linearRampToValueAtTime(180,t+.09);o.frequency.linearRampToValueAtTime(480,t+.18);sg.gain.setValueAtTime(0,t);sg.gain.linearRampToValueAtTime(v*.52,t+.005);sg.gain.exponentialRampToValueAtTime(.001,t+.22);o.start(t);o.stop(t+.24);}
  else if(type==='subbass'){const sg=GG(v*.85);const o=ctx.createOscillator();o.type='sine';o.frequency.value=52;o.connect(FF(20000,'lowpass',sg));sg.gain.setValueAtTime(0,t);sg.gain.linearRampToValueAtTime(v*.85,t+.01);sg.gain.linearRampToValueAtTime(v*.5,t+.12);sg.gain.exponentialRampToValueAtTime(.001,t+.42);o.start(t);o.stop(t+.48);}
  else if(type==='drone'){const dg=GG(v*.4);const fi=FF(280,'lowpass',dg);const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=41;o.connect(fi);const o2=ctx.createOscillator();o2.type='sine';o2.frequency.value=82;o2.connect(dg);dg.gain.setValueAtTime(0,t);dg.gain.linearRampToValueAtTime(v*.4,t+.06);dg.gain.exponentialRampToValueAtTime(.001,t+.75);o.start(t);o.stop(t+.8);o2.start(t);o2.stop(t+.8);}
  else if(type==='fx_dark'){const fg=GG(v*.62);const fi=FF(500,'lowpass',fg);const o=ctx.createOscillator();o.type='sawtooth';o.connect(fi);o.frequency.setValueAtTime(220,t);o.frequency.exponentialRampToValueAtTime(45,t+.28);const n=mkN('pink',.15);n.connect(FF(900,'bandpass',fg));fg.gain.setValueAtTime(0,t);fg.gain.linearRampToValueAtTime(v*.62,t+.001);fg.gain.exponentialRampToValueAtTime(.001,t+.3);o.start(t);o.stop(t+.32);n.start(t);n.stop(t+.2);}
  else if(type==='reverse'){const rg=GG(v*.5);const n=mkN('pink',.25);n.connect(FF(2800,'lowpass',rg));rg.gain.setValueAtTime(0,t);rg.gain.linearRampToValueAtTime(v*.5,t+.18);rg.gain.exponentialRampToValueAtTime(.001,t+.22);n.start(t);n.stop(t+.25);}
}
const AN=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
function nF(note,oct){const idx=AN.indexOf(note);return 440*Math.pow(2,(idx-9+(oct-4)*12)/12);}
function playMel(type,note,oct,vel,when,sd){
  if(!ctx)return;const t=Math.max(ctx.currentTime,(when||ctx.currentTime));const freq=nF(note||'C',oct||4);const v=Math.min(1.2,(vel||.7)*mvol);const p=sd||defSD(type);
  const eG=ctx.createGain();eG.gain.value=0;const fi=ctx.createBiquadFilter();fi.type='lowpass';fi.frequency.value=p.filterCutoff||3000;fi.Q.value=p.filterRes||1;fi.connect(eG);
  if(p.reverb>0){const rL=ctx.sampleRate*(p.reverb*2.5);const rB=ctx.createBuffer(2,rL,ctx.sampleRate);for(let c=0;c<2;c++){const dd=rB.getChannelData(c);for(let i=0;i<rL;i++)dd[i]=(Math.random()*2-1)*Math.pow(1-i/rL,2);}const rv=ctx.createConvolver();rv.buffer=rB;const rg=ctx.createGain();rg.gain.value=p.reverb*.65;rg.connect(mGain);eG.connect(rv);rv.connect(rg);}
  if(p.chorus>0){const dl=ctx.createDelay(.05);dl.delayTime.value=.025+p.chorus*.02;const cg=ctx.createGain();cg.gain.value=p.chorus*.45;eG.connect(dl);dl.connect(cg);cg.connect(mGain);}
  if(p.dist>0){const ws=ctx.createWaveShaper();const k=p.dist*300;const cv=new Float32Array(256);for(let i=0;i<256;i++){const x=i*2/256-1;cv[i]=(Math.PI+k)*x/(Math.PI+k*Math.abs(x));}ws.curve=cv;eG.connect(ws);ws.connect(mGain);}else eG.connect(mGain);
  // Lo-fi chain: tape saturation + vinyl noise + low-cut
  if(p.lofi&&p.lofi>0){const lf=ctx.createBiquadFilter();lf.type='lowpass';lf.frequency.value=4000-p.lofi*2800;lf.connect(mGain);eG.connect(lf);const vn=mkN('pink',.15+p.lofi*.3);const vg=ctx.createGain();vg.gain.value=p.lofi*.06;vn.connect(vg);vg.connect(mGain);vn.start(t);vn.stop(t+.15+p.lofi*.3);}
  if(p.lfoRate&&p.lfoDepth){const lfo=ctx.createOscillator();lfo.type='sine';lfo.frequency.value=p.lfoRate;const lg=ctx.createGain();lg.gain.value=0;lfo.connect(lg);if(p.lfoTarget==='filter'){lg.gain.value=p.lfoDepth*1000;lg.connect(fi.frequency);}else if(p.lfoTarget==='volume'){lg.gain.value=p.lfoDepth*.3;lg.connect(eG.gain);}lfo.start(t);lfo.stop(t+2);}
  const oT=p.oscType||'sawtooth';let dur=.8;
  if(type==='synth_lead'){[0,7].forEach(dt=>{const o=ctx.createOscillator();o.type=oT;o.frequency.value=freq;o.detune.value=(p.detune||0)+dt;o.connect(fi);o.start(t);o.stop(t+dur);});}
  else if(type==='synth_pad'){[-12,-5,0,5,12].forEach(dd=>{const o=ctx.createOscillator();o.type=oT;o.frequency.value=freq;o.detune.value=(p.detune||0)+dd;o.connect(fi);o.start(t);o.stop(t+1.4);});dur=1.4;}
  else if(type==='bass'){[freq/2,freq/2].forEach((f2,i)=>{const o=ctx.createOscillator();o.type=i?'sine':'sawtooth';o.frequency.value=f2;o.connect(fi);o.start(t);o.stop(t+.5);});dur=.5;}
  else if(type==='keys'){[[1,1],[2,.5],[3,.25],[4,.15],[6,.08],[8,.04]].forEach(([h,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.6;o.type='sine';o.frequency.value=freq*h;o.connect(og);og.connect(mGain);og.gain.setValueAtTime(a*v*.6,t);og.gain.exponentialRampToValueAtTime(a*v*.01,t+1.8);o.start(t);o.stop(t+2);});return;}
  else if(type==='supersaw'){// 7 detuned saws — EDM lead
    const detunes=[-34,-22,-11,0,11,22,34];detunes.forEach(dt=>{const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq;o.detune.value=(p.detune||0)+dt;o.connect(fi);o.start(t);o.stop(t+dur);});}
  else if(type==='supersaw_pad'){// 7 detuned saws wide pad
    const detunes=[-40,-25,-12,0,12,25,40];detunes.forEach(dt=>{const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq;o.detune.value=(p.detune||0)+dt;o.connect(fi);o.start(t);o.stop(t+1.6);});dur=1.6;}
  else if(type==='acid_bass'){// TB-303 style — resonant filter sweep
    const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq/2;o.connect(fi);fi.type='lowpass';fi.frequency.setValueAtTime(Math.max(1,p.filterCutoff||200),t);fi.Q.value=p.filterRes||12;fi.frequency.exponentialRampToValueAtTime(Math.max(1,Math.min(18000,p.filterCutoff*8||3000)),t+.08);fi.frequency.exponentialRampToValueAtTime(Math.max(1,p.filterCutoff||200),t+.35);o.start(t);o.stop(t+.5);dur=.5;}
  else if(type==='rave_stab'){// Short sharp chord hit
    [0,4,7].forEach(semi=>{const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq*Math.pow(2,semi/12);o.connect(fi);o.start(t);o.stop(t+.18);});dur=.18;}
  else if(type==='deep_bass'){// Deep house bass — filtered slow attack
    const o=ctx.createOscillator();o.type='sine';const o2=ctx.createOscillator();o2.type='sawtooth';o2.frequency.value=freq/2;const og2=ctx.createGain();og2.gain.value=v*.2;o2.connect(og2);og2.connect(fi);o.frequency.value=freq/2;o.connect(fi);fi.frequency.setValueAtTime(300,t);fi.frequency.linearRampToValueAtTime(p.filterCutoff||800,t+.25);o.start(t);o.stop(t+.8);o2.start(t);o2.stop(t+.8);dur=.8;}
  else if(type==='dub_bass'){// Reggae dub bass with wobble
    const o=ctx.createOscillator();o.type='sine';o.frequency.value=freq/2;o.detune.value=p.detune||0;o.connect(fi);const lfo=ctx.createOscillator();lfo.type='sine';lfo.frequency.value=3;const lg=ctx.createGain();lg.gain.value=8;lfo.connect(lg);lg.connect(o.frequency);lfo.start(t);lfo.stop(t+.9);o.start(t);o.stop(t+.9);dur=.9;}
  else if(type==='skank_guitar'){// Reggae muted offbeat chop
    [0,5,9].forEach(semi=>{const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq*Math.pow(2,semi/12);o.connect(fi);o.start(t);o.stop(t+.09);});fi.frequency.value=1800;dur=.09;}
  else if(type==='steelpan'){// Caribbean steel drum — additive with metallic ring
    [[1,1],[2.15,.5],[4.22,.25],[6.44,.1]].forEach(([r,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.55;o.type='sine';o.frequency.value=freq*r;o.connect(og);og.connect(mGain);og.gain.setValueAtTime(a*v*.55,t);og.gain.exponentialRampToValueAtTime(.001,t+1.2);o.start(t);o.stop(t+1.3);});return;}
  else if(type==='dub_siren'){// Descending pitch reggae siren — use return to bypass ADSR
    const o=ctx.createOscillator();o.type='sine';o.frequency.setValueAtTime(Math.max(1,freq*3),t);o.frequency.exponentialRampToValueAtTime(Math.max(1,freq*.5),t+.8);const sg=ctx.createGain();sg.gain.value=0;sg.connect(mGain);o.connect(sg);sg.gain.setValueAtTime(0,t);sg.gain.linearRampToValueAtTime(v*.7,t+.02);sg.gain.setValueAtTime(v*.7,t+.75);sg.gain.exponentialRampToValueAtTime(.001,t+.88);o.start(t);o.stop(t+.9);return;}
  else if(type==='sitar'){// Indian sitar — pluck with sympathetic buzz
    const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq;o.detune.value=p.detune||0;o.connect(fi);const buzz=ctx.createOscillator();buzz.type='sawtooth';buzz.frequency.value=freq*1.005;const bg=ctx.createGain();bg.gain.value=v*.15;buzz.connect(bg);bg.connect(fi);const n=mkN('white',.02);n.connect(fi);fi.frequency.setValueAtTime(p.filterCutoff||4000,t);fi.frequency.exponentialRampToValueAtTime(800,t+.5);o.start(t);o.stop(t+.8);buzz.start(t);buzz.stop(t+.8);n.start(t);n.stop(t+.025);dur=.8;}
  else if(type==='mbira'){// African thumb piano — metallic bright pluck
    [[1,1],[3.5,.4],[7.2,.15]].forEach(([r,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.5;o.type='sine';o.frequency.value=freq*r;o.connect(og);og.connect(mGain);og.gain.setValueAtTime(a*v*.5,t);og.gain.exponentialRampToValueAtTime(.001,t+.6);o.start(t);o.stop(t+.65);});return;}
  else if(type==='gamelan'){// Indonesian metallic bell cluster
    [[1,1],[2.04,.5],[3.12,.3],[4.28,.15],[5.44,.07]].forEach(([r,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.45;o.type='sine';o.frequency.value=freq*r;o.connect(og);og.connect(mGain);og.gain.setValueAtTime(a*v*.45,t);og.gain.exponentialRampToValueAtTime(.001,t+1.8);o.start(t);o.stop(t+1.9);});return;}
  else if(type==='noise_sweep'){// Filtered noise riser — use return to bypass ADSR
    const n=mkN('white',.9);const nfi=ctx.createBiquadFilter();nfi.type='lowpass';nfi.frequency.setValueAtTime(Math.max(1,p.filterCutoff||80),t);nfi.frequency.exponentialRampToValueAtTime(18000,t+.8);nfi.Q.value=Math.max(0.1,p.filterRes||2);const ng=ctx.createGain();ng.gain.value=0;n.connect(nfi);nfi.connect(ng);ng.connect(mGain);ng.gain.setValueAtTime(0,t);ng.gain.linearRampToValueAtTime(v*.55,t+.1);ng.gain.setValueAtTime(v*.55,t+.75);ng.gain.exponentialRampToValueAtTime(.001,t+.88);n.start(t);n.stop(t+.9);return;}
  else if(type==='pluck'){const o=ctx.createOscillator();o.type='triangle';o.frequency.value=freq;o.connect(fi);const n=mkN('white',.02);n.connect(fi);fi.frequency.setValueAtTime(p.filterCutoff||3500,t);fi.frequency.exponentialRampToValueAtTime(400,t+.4);o.start(t);o.stop(t+.55);n.start(t);n.stop(t+.025);dur=.55;}
  else if(type==='strings'){[-8,-3,0,3,8].forEach(dd=>{const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq;o.detune.value=(p.detune||0)+dd;o.connect(fi);o.start(t);o.stop(t+1.8);});dur=1.8;}
  else if(type==='organ'){[[1,1],[2,.5],[3,.25],[4,.1]].forEach(([h,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.5;o.type='sine';o.frequency.value=freq*h;o.connect(og);og.connect(fi);o.start(t);o.stop(t+.8);});}
  else if(type==='bell'){[[1,1],[2.756,.6],[5.404,.3],[8.001,.15]].forEach(([r,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.5;o.type='sine';o.frequency.value=freq*r;o.connect(og);og.connect(mGain);og.gain.setValueAtTime(a*v*.5,t);og.gain.exponentialRampToValueAtTime(.001,t+2.5);o.start(t);o.stop(t+2.6);});return;}
  else if(type==='brass'){const o1=ctx.createOscillator();o1.type='sawtooth';o1.frequency.value=freq;o1.connect(fi);const o2=ctx.createOscillator();o2.type='square';o2.frequency.value=freq;o2.connect(fi);fi.frequency.setValueAtTime(500,t);fi.frequency.linearRampToValueAtTime(p.filterCutoff||3000,t+.06);fi.frequency.linearRampToValueAtTime((p.filterCutoff||3000)*.6,t+.22);o1.start(t);o1.stop(t+.7);o2.start(t);o2.stop(t+.7);dur=.7;}
  else if(type==='sub_mel'){const o=ctx.createOscillator();o.type='sine';o.frequency.value=freq/2;o.connect(fi);const o2=ctx.createOscillator();o2.type='sine';o2.frequency.value=freq/2*1.002;o2.connect(fi);o.start(t);o.stop(t+1.2);o2.start(t);o2.stop(t+1.2);dur=1.2;}
  else if(type==='rhodes'){// Rhodes: sine fundamental + short attack harmonics + tremolo feel
    const parts=[[1,1],[2,.35],[3,.12],[4,.05]];parts.forEach(([h,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.55;o.type='sine';o.frequency.value=freq*h;o.detune.value=(p.detune||0);o.connect(og);og.connect(fi);og.gain.setValueAtTime(a*v*.55,t);og.gain.exponentialRampToValueAtTime(a*v*.55*.3,t+.8);o.start(t);o.stop(t+1.4);});dur=1.4;}
  else if(type==='lofi_piano'){// Detuned piano with grit
    [[1,1],[2,.4],[3,.15],[4,.06]].forEach(([h,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.5;o.type='sine';o.frequency.value=freq*h;o.detune.value=(p.detune||0)+(Math.random()*8-4);// slight random detune for tape feel
    o.connect(og);og.connect(fi);og.gain.setValueAtTime(a*v*.5,t);og.gain.exponentialRampToValueAtTime(.001,t+1.6);o.start(t);o.stop(t+1.7);});// vinyl crackle layer
    const n=mkN('pink',.3);const ng=ctx.createGain();ng.gain.value=v*.04;n.connect(ng);ng.connect(mGain);n.start(t);n.stop(t+.3);dur=1.6;}
  else if(type==='choir'){// Vowel filter approximation with multiple detuned sines
    [-7,-3,0,3,7,12].forEach(dt=>{const o=ctx.createOscillator();o.type='sine';o.frequency.value=freq;o.detune.value=(p.detune||0)+dt;o.connect(fi);o.start(t);o.stop(t+1.8);});// add second harmonic for "aah" vowel color
    const o2=ctx.createOscillator();o2.type='sine';o2.frequency.value=freq*2;const og2=ctx.createGain();og2.gain.value=v*.25;o2.connect(og2);og2.connect(fi);o2.start(t);o2.stop(t+1.8);dur=1.8;}
  else if(type==='harp'){// Plucked string simulation
    const o=ctx.createOscillator();o.type='triangle';o.frequency.value=freq;o.connect(fi);const o2=ctx.createOscillator();o2.type='sine';o2.frequency.value=freq*2;const og2=ctx.createGain();og2.gain.value=v*.3;o2.connect(og2);og2.connect(fi);fi.frequency.setValueAtTime(p.filterCutoff||5000,t);fi.frequency.exponentialRampToValueAtTime(800,t+.5);o.start(t);o.stop(t+.8);o2.start(t);o2.stop(t+.8);const n2=mkN('white',.02);n2.connect(fi);n2.start(t);n2.stop(t+.02);dur=.8;}
  else if(type==='guitar'){// Clean electric guitar - muted pluck
    const o=ctx.createOscillator();o.type='sawtooth';o.frequency.value=freq;o.detune.value=p.detune||0;o.connect(fi);const n=mkN('white',.015);n.connect(fi);fi.frequency.setValueAtTime(p.filterCutoff||2000,t);fi.frequency.exponentialRampToValueAtTime(300,t+.25);o.start(t);o.stop(t+.5);n.start(t);n.stop(t+.015);dur=.5;}
  else if(type==='flute'){// Breathy flute - sine + noise for breath
    const o=ctx.createOscillator();o.type='sine';o.frequency.value=freq;o.detune.value=p.detune||0;o.connect(fi);const n=mkN('white',.08);const ng=ctx.createGain();ng.gain.value=v*.12;n.connect(ng);ng.connect(fi);// vibrato
    if(p.lfoRate||true){const lfo=ctx.createOscillator();lfo.type='sine';lfo.frequency.value=p.lfoRate||5;const lg=ctx.createGain();lg.gain.value=p.lfoDepth?p.lfoDepth*8:4;lfo.connect(lg);lg.connect(o.frequency);lfo.start(t+.1);lfo.stop(t+1.2);}
    o.start(t);o.stop(t+1.1);n.start(t);n.stop(t+.08);dur=1.1;}
  else if(type==='marimba'){// Hollow wooden mallet
    [[1,1],[2,.3],[4,.1],[6,.04]].forEach(([h,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.6;o.type='sine';o.frequency.value=freq*h;o.connect(og);og.connect(mGain);og.gain.setValueAtTime(a*v*.6,t);og.gain.exponentialRampToValueAtTime(.001,t+.5);o.start(t);o.stop(t+.55);});return;}
  else if(type==='vibraphone'){// Metallic mallet with longer ring
    [[1,1],[2.01,.4],[3.01,.15],[4.02,.06]].forEach(([h,a])=>{const o=ctx.createOscillator();const og=ctx.createGain();og.gain.value=a*v*.55;o.type='sine';o.frequency.value=freq*h;o.connect(og);og.connect(mGain);og.gain.setValueAtTime(a*v*.55,t);og.gain.exponentialRampToValueAtTime(.001,t+1.5);o.start(t);o.stop(t+1.6);});return;}
  else if(type==='theremin'){// Eerie sine with pitch glide and wobble
    const o=ctx.createOscillator();o.type='sine';o.frequency.value=freq*.97;o.frequency.linearRampToValueAtTime(freq,t+.15);o.detune.value=p.detune||0;o.connect(fi);const lfo=ctx.createOscillator();lfo.type='sine';lfo.frequency.value=p.lfoRate||4;const lg=ctx.createGain();lg.gain.value=p.lfoDepth?p.lfoDepth*12:8;lfo.connect(lg);lg.connect(o.frequency);lfo.start(t);lfo.stop(t+1.2);o.start(t);o.stop(t+1.1);dur=1.1;}
  else if(type==='texture'){// Ambient noise texture
    const n=mkN('pink',.8);const n2=mkN('white',.8);const ng=ctx.createGain();ng.gain.value=v*.3;n.connect(fi);n2.connect(fi);fi.frequency.value=p.filterCutoff||400;n.start(t);n.stop(t+.75);n2.start(t);n2.stop(t+.75);dur=.75;}
  else if(type==='fx'){const o=ctx.createOscillator();o.type='sine';o.frequency.value=freq*2;o.frequency.linearRampToValueAtTime(freq*4,t+.3);o.connect(fi);const n=mkN('pink',.3);n.connect(fi);o.start(t);o.stop(t+.55);n.start(t);n.stop(t+.35);dur=.55;}
  const atk=p.attack||.01,dec2=p.decay||.1,sus=p.sustain||.5,rel=p.release||.2;
  const safeDur=Math.max(dur,atk+dec2+rel+.01); // guarantee dur always exceeds all envelope stages
  const eg=eG.gain;eg.cancelScheduledValues(t);eg.setValueAtTime(0,t);eg.linearRampToValueAtTime(v,t+atk);eg.linearRampToValueAtTime(v*sus,t+atk+dec2);eg.setValueAtTime(v*sus,t+Math.max(atk+dec2,safeDur-rel));eg.exponentialRampToValueAtTime(.001,t+safeDur);
}
function defSD(type){const D={
  synth_lead:{oscType:'sawtooth',filterCutoff:3000,filterRes:2,attack:.01,decay:.12,sustain:.5,release:.15,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.1,chorus:0,dist:0,detune:0,lofi:0},
  synth_pad:{oscType:'sawtooth',filterCutoff:1200,filterRes:1.5,attack:.18,decay:.2,sustain:.7,release:.4,lfoRate:.4,lfoDepth:.15,lfoTarget:'filter',reverb:.35,chorus:.3,dist:0,detune:0,lofi:0},
  supersaw:{oscType:'sawtooth',filterCutoff:4000,filterRes:2,attack:.008,decay:.1,sustain:.6,release:.2,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.15,chorus:0,dist:.08,detune:0,lofi:0},
  supersaw_pad:{oscType:'sawtooth',filterCutoff:1800,filterRes:1.2,attack:.2,decay:.2,sustain:.8,release:.5,lfoRate:.3,lfoDepth:.1,lfoTarget:'filter',reverb:.4,chorus:.4,dist:0,detune:0,lofi:0},
  acid_bass:{oscType:'sawtooth',filterCutoff:200,filterRes:12,attack:.005,decay:.15,sustain:.3,release:.1,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:0,chorus:0,dist:.1,detune:0,lofi:0},
  rave_stab:{oscType:'sawtooth',filterCutoff:5000,filterRes:2,attack:.002,decay:.05,sustain:.1,release:.08,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.1,chorus:0,dist:.05,detune:0,lofi:0},
  bass:{oscType:'sawtooth',filterCutoff:400,filterRes:2,attack:.008,decay:.1,sustain:.4,release:.1,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:0,chorus:0,dist:.05,detune:0,lofi:0},
  deep_bass:{oscType:'sine',filterCutoff:300,filterRes:1,attack:.15,decay:.2,sustain:.6,release:.3,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.05,chorus:0,dist:0,detune:0,lofi:0},
  dub_bass:{oscType:'sine',filterCutoff:300,filterRes:1,attack:.01,decay:.2,sustain:.7,release:.35,lfoRate:3,lfoDepth:.04,lfoTarget:'pitch',reverb:.15,chorus:0,dist:0,detune:0,lofi:.1},
  sub_mel:{oscType:'sine',filterCutoff:200,filterRes:1,attack:.01,decay:.2,sustain:.8,release:.3,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.05,chorus:0,dist:0,detune:0,lofi:0},
  rhodes:{oscType:'sine',filterCutoff:6000,filterRes:1,attack:.003,decay:.4,sustain:.3,release:.6,lfoRate:.8,lfoDepth:.04,lfoTarget:'volume',reverb:.25,chorus:.15,dist:0,detune:3,lofi:.1},
  lofi_piano:{oscType:'sine',filterCutoff:2500,filterRes:1,attack:.003,decay:.5,sustain:.2,release:.4,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.2,chorus:.1,dist:.08,detune:12,lofi:.4},
  choir:{oscType:'sine',filterCutoff:2000,filterRes:1.2,attack:.25,decay:.15,sustain:.8,release:.5,lfoRate:.35,lfoDepth:.08,lfoTarget:'filter',reverb:.5,chorus:.4,dist:0,detune:5,lofi:0},
  strings:{oscType:'sawtooth',filterCutoff:1800,filterRes:1,attack:.2,decay:.1,sustain:.8,release:.4,lfoRate:.3,lfoDepth:.1,lfoTarget:'pitch',reverb:.4,chorus:.4,dist:0,detune:0,lofi:0},
  pluck:{oscType:'triangle',filterCutoff:3500,filterRes:1,attack:.002,decay:.1,sustain:.1,release:.1,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.15,chorus:0,dist:0,detune:0,lofi:0},
  harp:{oscType:'triangle',filterCutoff:5000,filterRes:1,attack:.001,decay:.3,sustain:.05,release:.3,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.3,chorus:0,dist:0,detune:0,lofi:0},
  guitar:{oscType:'sawtooth',filterCutoff:2000,filterRes:1,attack:.003,decay:.15,sustain:.1,release:.15,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.1,chorus:.05,dist:.03,detune:0,lofi:.15},
  skank_guitar:{oscType:'sawtooth',filterCutoff:1800,filterRes:1,attack:.002,decay:.06,sustain:.05,release:.05,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.05,chorus:0,dist:.04,detune:0,lofi:.1},
  flute:{oscType:'sine',filterCutoff:4000,filterRes:1,attack:.04,decay:.05,sustain:.8,release:.2,lfoRate:5,lfoDepth:.04,lfoTarget:'pitch',reverb:.2,chorus:0,dist:0,detune:0,lofi:0},
  marimba:{oscType:'sine',filterCutoff:8000,filterRes:1,attack:.001,decay:.2,sustain:.05,release:.15,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.15,chorus:0,dist:0,detune:0,lofi:0},
  vibraphone:{oscType:'sine',filterCutoff:8000,filterRes:1,attack:.001,decay:.6,sustain:.1,release:.5,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.3,chorus:0,dist:0,detune:0,lofi:0},
  steelpan:{oscType:'sine',filterCutoff:8000,filterRes:1,attack:.001,decay:.4,sustain:.08,release:.3,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.25,chorus:0,dist:0,detune:0,lofi:0},
  organ:{oscType:'sine',filterCutoff:5000,filterRes:1,attack:.005,decay:.05,sustain:.9,release:.05,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.1,chorus:.1,dist:.02,detune:0,lofi:0},
  bell:{oscType:'sine',filterCutoff:8000,filterRes:1,attack:.001,decay:.5,sustain:.1,release:.8,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.5,chorus:0,dist:0,detune:0,lofi:0},
  brass:{oscType:'sawtooth',filterCutoff:3000,filterRes:2,attack:.04,decay:.15,sustain:.6,release:.2,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.15,chorus:0,dist:.05,detune:0,lofi:0},
  theremin:{oscType:'sine',filterCutoff:3000,filterRes:1,attack:.05,decay:.05,sustain:.9,release:.2,lfoRate:4,lfoDepth:.06,lfoTarget:'pitch',reverb:.3,chorus:0,dist:0,detune:0,lofi:0},
  dub_siren:{oscType:'sine',filterCutoff:5000,filterRes:1,attack:.01,decay:.1,sustain:.7,release:.2,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.35,chorus:0,dist:0,detune:0,lofi:0},
  sitar:{oscType:'sawtooth',filterCutoff:4000,filterRes:1,attack:.003,decay:.3,sustain:.2,release:.3,lfoRate:.5,lfoDepth:.03,lfoTarget:'pitch',reverb:.2,chorus:0,dist:0,detune:5,lofi:0},
  mbira:{oscType:'sine',filterCutoff:8000,filterRes:1,attack:.001,decay:.25,sustain:.05,release:.2,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.15,chorus:0,dist:0,detune:0,lofi:0},
  gamelan:{oscType:'sine',filterCutoff:8000,filterRes:1,attack:.001,decay:.8,sustain:.05,release:.5,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.4,chorus:0,dist:0,detune:0,lofi:0},
  noise_sweep:{oscType:'sine',filterCutoff:80,filterRes:2,attack:.1,decay:.3,sustain:.6,release:.3,lfoRate:0,lfoDepth:0,lfoTarget:'filter',reverb:.3,chorus:0,dist:0,detune:0,lofi:0},
  texture:{oscType:'sine',filterCutoff:400,filterRes:1,attack:.3,decay:.2,sustain:.7,release:.5,lfoRate:.2,lfoDepth:.3,lfoTarget:'filter',reverb:.6,chorus:.2,dist:.05,detune:0,lofi:.2},
  fx:{oscType:'sine',filterCutoff:2000,filterRes:3,attack:.05,decay:.2,sustain:.3,release:.3,lfoRate:2,lfoDepth:.5,lfoTarget:'filter',reverb:.3,chorus:.2,dist:.1,detune:0,lofi:0}
};return Object.assign({},D[type]||D.synth_lead);}
