function renderMix(dc){const mxs=document.createElement('div');mxs.className='mxs';const all=[...KITS[curKit].tracks.map((tr,ti)=>({name:tr.name,color:tr.color,isDrum:true,key:`${curKit}_${ti}`,vol:dVols[`${curKit}_${ti}`]||tr.vel,muted:dMuted[`${curKit}_${ti}`]||false})),...iTracks.map(t=>({name:t.def.label,color:t.def.color,isDrum:false,ref:t,vol:t.vol,muted:t.muted}))];all.forEach(tr=>{const strip=document.createElement('div');strip.className='mxstrip';const fw=document.createElement('div');fw.className='mxfw';const f=document.createElement('input');f.type='range';f.min=0;f.max=100;f.value=Math.round(tr.vol*100);f.step=1;f.className='mxf';const vEl=document.createElement('div');vEl.className='mxval';vEl.textContent=Math.round(tr.vol*100);f.addEventListener('input',()=>{const v=parseInt(f.value)/100;if(tr.isDrum)dVols[tr.key]=v;else tr.ref.vol=v;vEl.textContent=Math.round(f.value);});fw.appendChild(f);const mute=document.createElement('button');mute.className='mxm'+(tr.muted?' on':'');mute.textContent='M';mute.addEventListener('click',()=>{if(tr.isDrum)dMuted[tr.key]=!dMuted[tr.key];else tr.ref.muted=!tr.ref.muted;mute.className='mxm'+(tr.isDrum?dMuted[tr.key]:tr.ref.muted?' on':'');});const dot=document.createElement('div');dot.className='mxdot';dot.style.background=tr.color;dot.style.boxShadow=`0 0 5px ${tr.color}77`;const nm=document.createElement('div');nm.className='mxnm';nm.textContent=tr.name;strip.append(fw,vEl,mute,dot,nm);mxs.appendChild(strip);});dc.appendChild(mxs);}
function getIT(id){return iTracks.find(t=>t.id===id)||{};}
// SYNC
function syncMD(key,s){const mc=document.querySelector(`#tlr_${key} .ms[data-s="${s}"]`);if(mc){const sd=dGrid[key][s];const tr=KITS[curKit].tracks.find((_,ti)=>`${curKit}_${ti}`===key);mc.classList.toggle('on',!!(sd&&sd.on));if(sd&&sd.on&&tr){mc.style.background=tr.color;mc.style.opacity='.82';}else{mc.style.background='';mc.style.opacity='';}}};
function syncDS(key,s){const dc=document.getElementById(`dsc_${key}_${s}`);if(dc){const sd=dGrid[key][s];const tr=KITS[curKit].tracks.find((_,ti)=>`${curKit}_${ti}`===key);dc.classList.toggle('on',!!(sd&&sd.on));if(sd&&sd.on&&tr){dc.style.background=tr.color;dc.style.boxShadow=`inset 0 0 12px ${tr.color}44`;}else{dc.style.background='';dc.style.boxShadow='';}}}
function syncMR(tid,note,s){const mc=document.querySelector(`#tlr_${tid} .mr-c[data-s="${s}"][data-note="${note}"]`);if(mc){const t=iTracks.find(t=>t.id===tid);if(!t)return;const on=!!(t.rollData[note]&&t.rollData[note][s]);mc.classList.toggle('on',on);if(on){mc.style.background=t.def.color;mc.style.opacity='.82';}else{mc.style.background='';mc.style.opacity='';}}}
function syncPR(tid,note,s){const dc=document.getElementById(`prc_${tid}_${note.replace('#','s')}_${s}`);if(dc){const t=iTracks.find(t=>t.id===tid);if(!t)return;const on=!!(t.rollData[note]&&t.rollData[note][s]);dc.classList.toggle('on',on);if(on){dc.style.background=t.def.color;dc.style.opacity='.85';}else{dc.style.background='';dc.style.opacity='';}}}
// ADD INST
function addIT(type){iCtx();const def=ITYPES[type];const id=`it_${iCtr++}`;const rollData={};
  // Initialize all 12 notes × 7 octaves
  AN.forEach(n=>{for(let o=1;o<=7;o++){rollData[`${n}${o}`]=Array(stepCount).fill(0);}});
  const track={id,type,def,notes:def.notes,rollData,vol:.7,muted:false,octave:4,sd:defSD(type)};
  iTracks.push(track);buildAllTracks();selTrack(track.id,'inst',track);markDirty();
}
// PLAYBACK
function scheduler(){const sS=60/bpm/4;if(nextNT<ctx.currentTime)nextNT=ctx.currentTime+.01;while(nextNT<ctx.currentTime+.1){const s=curStep;const swOff=(s%2===1)?(swing/100)*sS*.48:0;const when=nextNT+swOff;KITS[curKit].tracks.forEach((tr,ti)=>{const key=`${curKit}_${ti}`;const sd=dGrid[key]&&dGrid[key][s];if(sd&&sd.on&&!dMuted[key])playDrum(tr.type,(dVols[key]||tr.vel)*(sd.vel||.8),when,dSD[key]||{});});iTracks.forEach(track=>{if(track.muted)return;
  // Support both old flat keys (note only) and new keys (note+octave)
  Object.keys(track.rollData).forEach(rollKey=>{
    if(track.rollData[rollKey]&&track.rollData[rollKey][s]){
      // Determine note and octave from key
      const hasOct=/\d$/.test(rollKey);
      const note=hasOct?rollKey.slice(0,-1):rollKey;
      const oct=hasOct?parseInt(rollKey.slice(-1)):track.octave;
      playMel(track.type,note,oct,track.vol,when,track.sd);
    }
  });
});const snap=s;setTimeout(()=>{document.querySelectorAll('.si').forEach((el,i)=>el.classList.toggle('on',i===snap));document.querySelectorAll('.bm').forEach((el,i)=>{el.style.color=i===snap?'var(--teal)':'';});document.querySelectorAll('.ms.playing').forEach(el=>el.classList.remove('playing'));document.querySelectorAll(`.ms[data-s="${snap}"]`).forEach(el=>el.classList.add('playing'));document.querySelectorAll('.mr-c.playing,.pr-c.playing,.ds.playing').forEach(el=>el.classList.remove('playing'));document.querySelectorAll(`.mr-c[data-s="${snap}"],.pr-c[data-s="${snap}"],.ds[data-s="${snap}"]`).forEach(el=>el.classList.add('playing'));document.querySelectorAll('.dlbl').forEach((el,i)=>{el.classList.toggle('cur',i===snap);});const bd=document.getElementById('barDisp');if(bd)bd.innerHTML=`Bar <span>${Math.floor(snap/4)+1}.${(snap%4)+1}</span>`;},Math.max(0,(nextNT-ctx.currentTime)*1000-10));nextNT+=sS;curStep=(s+1)%stepCount;}}
function startSeq(){if(isPlaying)return;iCtx();isPlaying=true;curStep=0;nextNT=ctx.currentTime+.05;seqInt=setInterval(scheduler,25);document.getElementById('btnPlay').className='btn playing';document.getElementById('btnPlay').textContent='⏸ Pause';document.getElementById('epill').textContent='Live';document.getElementById('edot').style.background='var(--pink)';}
function stopSeq(){isPlaying=false;clearInterval(seqInt);curStep=0;document.getElementById('btnPlay').className='btn hot';document.getElementById('btnPlay').textContent='▶ Play';document.getElementById('epill').textContent='Ready';document.getElementById('edot').style.background='var(--teal)';document.getElementById('barDisp').innerHTML='Bar <span>1.1</span>';document.querySelectorAll('.si').forEach(el=>el.classList.remove('on'));document.querySelectorAll('.ms.playing,.mr-c.playing,.pr-c.playing,.ds.playing').forEach(el=>el.classList.remove('playing'));document.querySelectorAll('.bm').forEach(el=>el.style.color='');}
